import pathlib

import index
from tests.conftest import VALID_DECISION, write_bundle, write_decision


def test_format_row_minimal() -> None:
    row = {"slug": "alpha", "path": "changes/x/design.md", "date": "2026-01-02", "summary": "did it"}
    assert index.format_row(row) == "- **[alpha](changes/x/design.md)** (2026-01-02) — did it"


def test_format_row_no_summary_fallback() -> None:
    assert "(no summary)" in index.format_row({"slug": "a", "path": "p", "date": "d"})


def test_format_row_supersedes() -> None:
    row = {"slug": "a", "path": "p", "date": "d", "summary": "s", "supersedes": "old"}
    assert index.format_row(row).endswith("_(supersedes old)_")


def test_format_row_superseded_by() -> None:
    row = {"slug": "a", "path": "p", "date": "d", "summary": "s", "superseded_by": "new"}
    assert index.format_row(row).endswith("_(superseded by new)_")


def test_render_empty_sections() -> None:
    out = index.render([], [])
    assert "## Changes\n\n_None._" in out
    assert "## Decisions\n\n_None._" in out


def test_render_orders_newest_first() -> None:
    bundles = [
        {"name": "2026-01-01.01-old", "slug": "old", "path": "p1", "date": "2026-01-01", "summary": "o"},
        {"name": "2026-01-09.01-new", "slug": "new", "path": "p2", "date": "2026-01-09", "summary": "n"},
    ]
    out = index.render(bundles, [])
    assert out.index("new") < out.index("old")


def test_full_render_snapshot(tmp_path: pathlib.Path) -> None:
    write_bundle(tmp_path, "2026-01-02.01-alpha", design="---\nsummary: shipped alpha\n---\n")
    write_decision(tmp_path, "2026-01-03-beta.md", VALID_DECISION)

    out = index.render(index.load_bundles(tmp_path), index.load_decisions(tmp_path))

    assert out == (
        "# Planning index\n"
        "\n"
        "_Generated by `just index` — do not edit._\n"
        "\n"
        "## Changes\n"
        "\n"
        "- **[alpha](changes/2026-01-02.01-alpha/design.md)** (2026-01-02) — shipped alpha\n"
        "\n"
        "## Decisions\n"
        "\n"
        "- **[beta](decisions/2026-01-03-beta.md)** (2026-01-03) — chose X over Y\n"
    )
